# Generated by Django 3.0.6 on 2020-05-05 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200505_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.Userinfo'),
        ),
        migrations.AlterField(
            model_name='cartinclude',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 14, 34, 32, 497959, tzinfo=utc)),
        ),
    ]
