# Generated by Django 3.0.6 on 2020-05-05 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20200505_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinclude',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 14, 40, 17, 810459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.UserLogin'),
        ),
    ]
