# Generated by Django 3.0.6 on 2020-05-05 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20200505_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.UserLogin', verbose_name='选择用户'),
        ),
        migrations.AlterField(
            model_name='cartinclude',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 15, 18, 51, 254643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cartinclude',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
        ),
        migrations.AlterField(
            model_name='orderinclude',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Orders'),
        ),
        migrations.AlterField(
            model_name='orderinclude',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.UserLogin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.ProductCatagory'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mall.UserLogin'),
        ),
    ]
