# Generated by Django 3.0.6 on 2020-05-05 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20200506_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinclude',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 16, 20, 11, 688919, tzinfo=utc)),
        ),
    ]
