# Generated by Django 3.0.6 on 2020-05-05 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_auto_20200506_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='userinfo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartinclude',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='main_pict',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
