# Generated by Django 3.0.6 on 2020-05-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_auto_20200506_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcatagory',
            old_name='catogary',
            new_name='catagory',
        ),
    ]
