# Generated by Django 3.0.6 on 2020-05-07 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_auto_20200507_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.UserLogin'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_company',
            field=models.CharField(default='无', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='finish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_money',
            field=models.FloatField(default=0),
        ),
    ]
