# Generated by Django 3.0.6 on 2020-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_auto_20200508_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='userinfo_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.IntegerField(choices=[(-1, '关闭'), (0, '等待支付'), (1, '等待发货'), (2, '已发货'), (3, '订单完成')], default=0),
        ),
    ]
