# Generated by Django 3.0.6 on 2020-05-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_auto_20200509_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.AddField(
            model_name='orders',
            name='address_line',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='d_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='d_telephone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
